version: '3.2'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend.dockerfile
    container_name: backend_newsletter
    image: r4deu51/backend_newsletter:1.0.0
    ports:
      - "3000:3000"